apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mongo-deployment
  labels:
    app: node-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-mongo
  template:
    metadata:
      labels:
        app: node-mongo
    spec:
      containers:
      - name: node-mongo
        image: mandipkaur/nagp-node-app
        ports:
        - containerPort: 3000
